name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * 0'  # Weekly SAST scan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        pytest

    - name: Run Bandit (SAST)
      run: |
        pip install bandit
        bandit -r .

    - name: Run Gitleaks (Secrets Scan)
      uses: gitleaks/gitleaks-action@v1
      with:
        config-path: .gitleaks.toml
