name: CI Security Pipeline

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Elke zondag om middernacht

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      # 1. Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installeer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Installeer dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. SAST-scan met Bandit
      - name: Run Bandit (SAST)
        run: bandit -r .
      
      # 5. Dependency check met Safety
      - name: Run Safety (Dependency Check)
        run: safety check --full-report

      # 6. Geheime sleutels en wachtwoorden detectie met Gitleaks
      - name: Run Gitleaks (Secrets Detection)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --verbose --redact

      # 7. Controleer of alle checks succesvol zijn
      - name: Check for warnings or errors
        if: failure()
        run: |
          echo "Er zijn veiligheidsproblemen gedetecteerd. De pull request wordt afgekeurd."
          exit 1
