name: Python CI

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Elke zondag om middernacht

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          python -m unittest discover
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Dependency Check
        run: |
         pip install safety
         safety check
      - name: Secret Scan
        uses: trufflesecurity/trufflehog@v2
        with:
          scanArguments: --regex --entropy=True
      - name: Dependency Check
        run: |
         pip install safety
         safety check
        continue-on-error: false

