name: Python CI

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # Runs weekly (every Sunday at midnight UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests (adjust if you have specific tests)
    - name: Run tests
      run: |
        pytest

    # Static analysis for SAST (Static Application Security Testing)
    - name: Static Analysis (SAST)
      run: |
        pip install bandit
        bandit -r .

    # Check dependencies for vulnerabilities
    - name: Dependency scan for vulnerabilities
      run: |
        pip install safety
        safety check --full-report

    # Check if secrets are exposed in the codebase
    - name: Check for secrets in the code
      uses: zricethezav/gitleaks-action@v1
      with:
        args: --no-gitignore --redact
